# Generated by Django 5.2.11 on 2026-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
